name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2.0.1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3.0.0
        with:
          arguments: check
      - uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: build/reports
